hrdb:
  build: .
  restart: always
  environment:
    - PORT=80
  ports:
   - "80:80"
  volumes:
   - /data/uploads/:/data/uploads/
  links:
   - hrdbmongo
hrdbmongo:
  restart: always
  ports:
    - "27017:27017"
  volumes:
   - /data/db/:/data/db/
  image: mongo:2.9
  container_name: hrdbmongo
  hostname:       hrdbmongo
  domainname:     hrdbmongo
