version: '2'

services:
  hrdb:
    build:
      context: .
    command: ["grunt", "test:client"]
    ports:
      - "9000:9000"
      - "35729:35729"
      - "5858:5858"
    volumes:
      - .:/vol/app/
  hrdbmongo:
    ports:
      - "27017:27017"
    volumes:
    - /data/db/:/data/db/
    image: mongo
    container_name: hrdbmongo
    hostname:       hrdbmongo
    domainname:     hrdbmongo
  hrdbselenium:
    image: selenium/standalone-chrome
    ports:
      - "5900:5900"
    container_name: hrdbselenium
    hostname:       hrdbselenium
    domainname:     hrdbselenium
